//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by Client.rc
//
#define IDD_ABOUTBOX                    100
#define IDR_MAINFRAME                   128
#define IDR_ClientTYPE                  129
#define IDD_BUILD                       131
#define IDR_MENU_REPORT                 131
#define IDD_FILE                        132
#define IDR_LIST                        133
#define IDC_DRAG                        134
#define IDC_MUTI_DRAG                   135
#define IDC_CURSOR3                     136
#define IDC_CURSOR4                     137
#define IDD_SETTINGS                    140
#define IDD_UPDATE_DLG                  144
#define IDR_FILEMANAGER                 146
#define IDR_TOOLBAR1                    147
#define IDB_TOOLBAR                     149
#define IDB_TOOLBAR_ENABLE              149
#define IDR_TOOLBAR2                    154
#define IDR_LOCAL_VIEW                  156
#define IDR_REMOTE_VIEW                 157
#define IDB_TOOLBAR_DISABLE             158
#define IDD_TRANSFERMODE_DLG            159
#define IDD_SCREENSPY                   160
#define IDD_DOWNEXEC                    162
#define IDD_WEBCAM                      163
#define IDI_WEBCAM                      164
#define IDB_ARROWDOWN                   165
#define IDB_ARROWUP                     166
#define IDD_KEYBOARD                    167
#define IDD_NEWFOLDER                   168
#define IDD_SYSTEM                      169
#define IDR_PSLIST                      170
#define IDD_SHELL                       171
#define IDR_BSS                         173
#define IDI_CMDSHELL                    177
#define IDI_KEYBOARD                    178
#define IDI_SYSTEM                      179
#define IDC_DOT                         182
#define IDR_MINIMIZE                    183
#define IDD_AUDIO                       184
#define IDI_AUDIO                       185
#define IDD_SYSINFO                     186
#define IDD_SERMANA                     187
#define IDI_IPS                         187
#define IDB_FILE                        188
#define IDR_SLIST                       188
#define IDI_OS                          188
#define IDD_SKIN_COLOUR                 188
#define IDB_PINGMU                      189
#define IDI_CPU                         189
//#define IDD_LOGIN                       189
#define IDB_KEYBOARD                    190
#define IDI_MEMORY                      190
#define IDB_CMDSHELL                    191
#define IDD_CHANGE_GROUP                191
#define IDI_DISK                        191
#define IDB_SYSTEM                      192
#define IDI_USERNAME                    192
#define IDB_AUDIO                       193
#define IDI_TIME                        193
#define IDR_LOG                         193
#define IDB_WEBCAM                      194
#define IDD_SERVICE                     194
#define IDR_ADSL_COPY                   194
#define IDB_SERVICE                     195
#define IDR_SSLIST                      195
#define IDB_REGEDIT                     196
#define IDI_DOUBLE                      196
#define IDB_BIND                        197
#define IDB_SETTING                     198
#define IDB_UPDATE                      199
#define IDB_BUILD                       200
#define IDB_ABOUT                       201
#define IDB_EXIT                        202
#define IDD_ATTACK_DIALOG               202
#define IDI_STR_ICON                    203
#define IDD_IPUPDATE                    203
#define IDI_DWORD_ICON                  204
#define IDD_CUSTOMATTACK_DIALOG         204
#define IDI_REG_ICON                    205
#define IDI_ICOINFO_PROCESS             205
#define IDD_REG_DIALOG                  206
#define IDI_SER_ICON                    206
#define IDI_ICOINFO_APPWIN              206
#define IDI_DIR_ICON                    207
#define IDI_FATHER_ICON                 208
#define IDI_ICON_DIALU                  208
#define IDI_ONLINE                      210
#define IDR_REGT_MENU                   211
#define IDD_SETTING                     211
#define IDD_REGDATA_DLG                 212
#define IDI_ICON83                      212
#define IDR_REGL_MENU                   213
#define IDD_BIND                        213
#define IDI_ICON2                       213
#define IDB_SPLASH                      214
#define IDI_ICON3                       214
#define IDI_ICON4                       215
#define IDR_UPX                         216
#define IDI_ICON5                       216
#define IDR_FSG                         217
#define IDI_ICON6                       217
#define IDI_ICON7                       218
#define IDI_SHIPIN                      219
#define IDI_ICON1                       220
#define IDI_USER                        220
#define IDI_ICON10                      221
#define IDI_ICON11                      222
#define IDI_ICON12                      223
#define IDD_UPDATE                      224
#define IDR_TOOLBAR3                    224
#define IDI_ICON13                      224
#define IDD_INSTALL                     225
#define IDI_ICON14                      225
#define IDR_WLIST                       226
#define IDI_ICON15                      226
#define IDR_ILIST                       227
#define IDI_ICOFILE                     227
#define IDR_SKIN                        227
#define IDI_ANTI                        228
#define IDR_TOOLBAR4                    229
#define IDI_ICON9                       229
#define IDI_ICON19                      230
#define IDB_MENU                        230
#define IDB_BARNEW                      231
#define IDI_ICON20                      231
#define IDI_ICON21                      232
#define IDI_ICON22                      233
#define IDD_MSGBOX                      234
#define IDI_ICON23                      234
#define IDI_ICON24                      235
#define IDI_ICON25                      236
#define IDI_ICON26                      237
#define IDD_LOCK_DIALOG                 237
#define IDD_PROXY                       238
#define IDI_ICON27                      238
#define IDD_SHORTCUTS                   239
#define IDI_ICON28                      239
#define IDD_FLOWATTACK_DIALOG           240
#define IDI_ICON29                      240
#define IDI_ICON30                      241
#define IDI_ICON31                      242
#define IDI_ICON32                      243
#define IDI_ICON33                      244
#define IDI_ICON34                      245
#define IDI_ICON35                      246
#define IDI_ICON36                      247
#define IDI_ICON37                      248
#define IDI_ICON38                      249
#define IDI_ICON39                      250
#define IDI_ICON40                      251
#define IDI_ICON41                      252
#define IDI_ICON42                      253
#define IDI_ICON43                      254
#define IDI_ICON44                      255
#define IDI_ICON45                      256
#define IDI_ICON46                      257
#define IDI_ICON47                      258
#define IDI_ICON48                      259
#define IDI_ICON49                      260
#define IDI_ICON50                      261
#define IDI_ICON51                      262
#define IDI_ICON52                      263
#define IDI_ICON53                      264
#define IDI_ICON54                      265
#define IDI_ICON55                      266
#define IDI_ICON56                      267
#define IDI_ICON57                      268
#define IDI_ICON58                      269
#define IDI_ICON59                      270
#define IDI_ICON60                      271
#define IDI_ICON61                      272
#define IDI_ICON62                      273
#define IDI_ICON63                      274
#define IDI_ICON64                      275
#define IDI_ICON65                      276
#define IDI_ICON66                      277
#define IDI_ICON67                      278
#define IDI_ICON68                      279
#define IDI_ICON69                      280
#define IDI_ICON70                      281
#define IDI_ICON71                      282
#define IDI_ICON72                      283
#define IDI_ICON73                      284
#define IDI_ICON74                      285
#define IDI_ICON75                      286
#define IDI_ICON76                      287
#define IDI_ICON77                      288
#define IDI_ICON78                      289
#define IDI_ICON79                      290
#define IDI_ICON80                      291
#define IDI_ICON81                      292
#define IDI_ICON82                      293
#define IDI_ICON8                       294
#define IDI_ICON18                      295
#define IDI_ICON17                      296
#define IDI_ICON16                      297
#define IDC_username                    996
#define IDC_userpass                    997
//#define IDC_LOGIN                       998
#define IDC_LIST_TARGET                 1002
#define IDC_TARGET_WEB                  1003
#define IDC_ATTCKPORT                   1004
#define IDC_LIST_REMOTE                 1005
#define IDC_THREADNUMS                  1005
#define IDC_LIST_LOCAL                  1006
#define IDC_LOCAL_PATH                  1007
#define IDC_HOSTNUMS                    1007
#define IDC_SLIDER4                     1007
#define IDC_REMOTE_PATH                 1008
#define IDC_SLIDER_THREAD               1008
#define IDC_STATIC_REMOTE               1009
#define IDC_ATTACKTIMES                 1009
#define IDC_CONFIRM                     1010
#define IDC_SLIDER_TIME                 1010
#define IDC_PORT                        1011
#define IDC_LISTEN_PORT                 1011
#define IDC_SPIN_NUM                    1011
#define IDC_SLIDER11                    1011
#define IDC_OVERWRITE                   1012
#define IDC_CONNECT_MAX                 1012
#define IDC_PORT2                       1012
#define IDC_NEWAUTO                     1012
#define IDC_ADDITION                    1013
#define IDC_SELECTHOST                  1013
#define IDC_COMBO_DNSIP                 1013
#define IDC_JUMP                        1014
#define IDC_ADDTASK                     1014
#define IDC_SEND_RATE                   1014
#define IDC_SLIDER10                    1014
#define IDC_OVERWRITE_ALL               1015
#define IDC_COMBO_MODEL                 1015
#define IDC_ADDITION_ALL                1016
#define IDC_STARTVAR                    1016
#define IDC_SPIN_RATE                   1016
#define IDC_JUMP_ALL                    1017
#define IDC_ENDVAR                      1017
#define IDC_CANCEL                      1018
#define IDC_TIPS                        1019
#define IDC_STATIC_TIP                  1020
#define IDC_URL                         1021
#define IDC_EDIT_DECIMAL                1021
#define IDC_ENCODE                      1022
#define IDC_DNS_STRING                  1022
#define IDC_EDIT_HEX                    1022
#define IDC_REMOTE_HOST                 1023
#define IDC_REMOTE_PORT                 1024
#define IDC_STATIC_2                    1024
#define IDC_SLIDER6                     1024
#define IDC_PROXY_HOST                  1025
#define IDC_STATIC_1                    1025
#define IDC_PROXY_PORT                  1026
#define IDC_STATIC_3                    1026
#define IDC_PROXY_USER                  1027
#define IDC_STATIC_4                    1027
#define IDC_SLIDER2                     1027
#define IDC_PROXY_PASS                  1028
#define IDC_STATIC_6                    1028
#define IDC_EDIT_DNSUSER                1028
#define IDC_EDIT                        1029
#define IDC_STATIC_7                    1029
#define IDC_EDIT_DNSPASS                1029
#define IDC_RESETPORT                   1030
#define IDC_STATIC_8                    1030
#define IDC_EDIT_DNSDOMAIN              1030
#define IDC_FOLDERNAME                  1031
#define IDC_STATIC_9                    1031
#define IDC_BTN_DNSUPDATE               1031
#define IDC_SLIDER7                     1031
#define IDC_STATIC_10                   1032
#define IDC_SLIDER8                     1032
#define IDC_STATIC_11                   1033
#define IDC_SLIDER9                     1033
#define IDC_LIST_PROCESS                1034
#define IDC_TAB                         1035
#define IDC_EDIT_TIP                    1035
#define IDC_LIST_WINDOWS                1036
#define IDC_STATIC_20                   1036
#define IDC_SLIDER1                     1036
#define IDC_LIST_DIALUPASS              1037
#define IDC_START_ATTACK                1037
#define IDC_BUILD                       1038
#define IDC_LIST_SERVER                 1038
#define IDC_START_STOP                  1038
#define IDC_SLIDER3                     1038
#define IDC_EXIT1                       1039
#define IDC_SLIDER5                     1039
#define IDC_CONNECT_AUTO                1040
#define IDC_STATIC_VER                  1041
#define IDC_ENABLE_HTTP                 1043
#define IDC_CHECK_AUTH                  1048
#define IDC_CHECK_PROXY                 1049
#define IDC_TEST_PROXY                  1050
#define IDC_TEST_MASTER                 1051
#define IDC_SYSTEM_TIPS                 1052
#define IDC_SHOWTIPS                    1052
#define IDC_DISABLE_POPTIPS             1053
#define IDC_SEND_LOCALAUDIO             1054
#define IDC_SAVEAS_DEFAULT              1054
#define IDC_SERVICE_DISPLAYNAME         1058
#define IDC_SERVICE_DESCRIPTION         1059
#define IDC_EDIT_NAME                   1060
#define IDC_INFO_LIST                   1060
#define IDC_INSTALL_LIST                1060
#define IDC_EDIT_DISP                   1061
#define IDC_LIST                        1061
#define IDC_LIST_SEV                    1061
#define IDC_EDIT_DESC                   1062
#define IDC_LIST_WTS                    1062
#define IDC_PATH_NAME                   1063
#define IDC_KEY                         1063
#define IDC_ADMIN                       1063
#define IDC_EXIT_PROXY                  1063
#define IDC_BUTTON_OK                   1064
#define IDC_CREAT                       1064
#define IDC_IP                          1064
#define IDC_DDOS_ATTACK                 1064
#define IDC_PATH                        1065
#define IDC_OPEN3389                    1065
#define IDC_DNSID                       1065
#define IDC_SET_SKIN                    1065
#define IDC_STOP                        1066
#define IDC_RADIO1                      1066
#define IDC_DNSPASS                     1066
#define IDC_STOP_FIRE                   1066
#define IDC_GUEST                       1067
#define IDC_RADIO2                      1067
#define IDC_CHANGE                      1068
#define IDC_RADIO3                      1068
#define IDC_ADDR                        1069
#define IDC_RADIO4                      1069
#define IDC_CONNECT                     1070
#define IDC_RADIO5                      1070
#define IDC_CHECK_PROCESS               1070
#define IDC_PORTDNS                     1071
#define IDC_DELETE                      1071
#define IDC_CLOSE3389                   1071
#define IDC_PORTMAP                     1072
#define IDC_RADIO7                      1072
#define IDC_SAVE                        1072
#define IDC_PROGRESS_3389               1072
#define IDC_RADIO8                      1073
#define IDC_SELECT_ICO                  1073
#define IDC_FORCE                       1073
#define IDC_TREE                        1074
#define IDC_RADIO10                     1074
#define IDC_BIG                         1074
#define IDC_ONLINE_INFO_LIST            1074
#define IDC_RADIO11                     1075
#define IDC_SUIJI                       1075
#define IDC_DAILI                       1075
#define IDC_LAN_CONNECT                 1075
#define IDC_RADIO12                     1076
#define IDC_KILL                        1076
#define IDC_DAILI_DAILI                 1076
#define IDC_SERVICE_LIST                1077
#define IDC_RADIO13                     1077
#define IDC_NOTEPAD                     1077
#define IDC_UPDATE                      1078
#define IDC_CMD                         1078
#define IDC_RADIO_NOIP                  1078
#define IDC_EXIT                        1079
#define IDC_COMBO_GROUP                 1079
#define IDC_CLAC                        1079
#define IDC_RADIO_3322                  1079
#define IDC_RADIO6                      1080
#define IDC_MSPAINT                     1080
#define IDC_SIGNNOIP                    1080
#define IDC_MSTSC                       1081
#define IDC_SIGN3322                    1081
#define IDC_LINSTEN_PORT                1082
#define IDC_TASKMGR                     1082
#define ID_UPDATE                       1082
#define IDC_MAX_CONNECT                 1083
#define IDC_GPEDIT                      1083
#define IDC_CHECK_TIME                  1084
#define IDC_COMPMGMT                    1084
#define IDC_IPUPDATE                    1084
#define IDC_OPEN_SOUND                  1085
#define IDC_DIRECTX                     1085
#define IDC_GETWAN                      1085
#define IDC_CLOSE_TIPS                  1086
#define IDC_SERVICES                    1086
#define IDC_APPLY                       1087
#define IDC_REGEDIT                     1087
#define IDC_ZITI                        1087
#define IDC_SHOW                        1088
#define IDC_EDIT1                       1088
#define IDC_IEXPRESS                    1088
#define IDC_EDIT_SVCNAME                1088
#define IDC_SET                         1088
#define IDC_SEND                        1089
#define IDC_SELECT1                     1089
#define IDC_SETAGAIN                    1089
#define IDC_EDIT2                       1090
#define IDC_EDIT_SCNAME                 1090
#define IDC_UNLOCK                      1090
#define IDC_SELECT2                     1091
#define IDC_EDIT3                       1092
#define IDC_SYSTEM_TAB                  1092
#define IDC_EDIT_SHELP                  1092
#define IDC_SELECT3                     1093
#define IDC_EDIT4                       1094
#define IDC_BIAOZHI                     1094
#define IDC_SELECT4                     1095
#define IDC_EDIT5                       1096
#define IDC_VipName                     1096
#define IDC_SELECT5                     1097
#define IDC_VipPass                     1097
#define IDC_BUTTON2                     1098
#define IDC_BUTTON3                     1099
#define IDC_STATIC_ICON                 1099
#define IDC_ICO                         1100
#define IDC_STATIC_TIPS                 1101
#define IDC_DNS1                        1102
#define IDC_PORT1                       1103
#define IDC_CHUANSHU                    1104
#define IDC_DNS                         1105
#define IDC_AUDIO                       1105
#define IDC_USER                        1106
#define IDC_SERVICE_DISPLAY             1106
#define IDC_ONLINE_WAY                  1106
#define IDC_PASS                        1107
#define IDC_SERVICE_DESCRIPT            1107
#define IDC_ONLINE_GROUP                1107
#define IDC_GROUPNAME                   1108
#define IDC_INSTALL_WAY                 1108
#define IDC_LOCALIP                     1109
#define IDC_VERSION                     1109
#define IDC_EDIT_TEXT                   1110
#define IDC_PROCESS                     1110
#define IDC_SERVICE_NAME                1111
#define IDC_GREEN                       1111
#define IDC_DNS2                        1112
#define IDC_STATIC_ICON1                1113
#define IDC_DEL_MYSELF                  1113
#define IDC_STATIC_ICON2                1114
#define IDC_DISABLE_SOUND               1114
#define IDC_STATIC_ICON3                1115
#define IDC_STATIC_ICON4                1116
#define IDC_TEST                        1116
#define IDC_EDIT_TITLE                  1117
#define IDC_SOCKS5                      1127
#define ID_SETLOCK                      1133
#define ID_QUIT                         1134
#define ID_LOCAL_TOOLBAR                0x5001
#define ID_REMOTE_TOOLBAR               0x5002
#define ID_APP_PWD                      32771
#define IDM_START                       32771
#define IDM_FILEMANAGER                 32772
#define IDM_STOP                        32772
#define IDM_SHUTDOWN                    32773
#define IDM_DELETE_LIST                 32773
#define IDM_REBOOT                      32774
#define IDM_TRANSFER                    32775
#define IDM_RENAME                      32776
#define IDM_DELETE                      32777
#define IDM_NEWFOLDER                   32778
#define IDM_PROPERTY                    32779
#define IDT_LOCAL_PREV                  32780
#define IDT_LOCAL_COPY                  32781
#define IDT_LOCAL_DELETE                32782
#define IDT_LOCAL_VIEW                  32783
#define ID_MENU_DEL                     32783
#define IDT_LOCAL_NEWFOLDER             32784
#define ID_MENU_REF                     32786
#define ID_MENU_START                   32787
#define ID_MENU_STOP                    32788
#define IDT_REMOTE_PREV                 32790
#define IDT_REMOTE_COPY                 32791
#define IDT_REMOTE_DELETE               32792
#define ID_MENU_START_AUTO              32792
#define IDT_REMOTE_NEWFOLDER            32793
#define ID_MENU_START_MANAGER           32793
#define IDT_REMOTE_VIEW                 32794
#define ID_MENU_START_DISABLE           32794
#define IDT_REMOTE_STOP                 32795
#define IDT_LOCAL_STOP                  32797
#define IDM_LOCAL_BIGICON               32798
#define IDM_LOCAL_SMALLICON             32799
#define IDM_LOCAL_LIST                  32800
#define IDM_LOCAL_REPORT                32801
#define IDM_REMOTE_BIGICON              32802
#define IDM_REMOTE_SMALLICON            32803
#define IDM_REMOTE_LIST                 32804
#define IDM_REMOTE_REPORT               32805
#define IDM_SCREENSPY                   32806
#define IDM_DOWNEXEC                    32807
#define IDM_WEBCAM                      32808
#define IDM_REMOVE                      32809
#define IDM_KEYBOARD                    32810
#define IDM_REFRESH                     32811
#define IDM_SYSTEM                      32812
#define IDM_KILLPROCESS                 32813
#define IDM_REFRESHPSLIST               32814
#define IDM_REMOTESHELL                 32815
#define IDM_LOGOFF                      32818
#define IDM_SELECT_ALL                  32820
#define IDM_UNSELECT_ALL                32821
#define IDM_OPEN_URL_SHOW               32825
#define IDM_OPEN_URL_HIDE               32827
#define IDM_CLEANEVENT                  32828
#define IDM_HIDE                        32829
#define IDM_SHOW                        32830
#define IDM_EXIT                        32831
#define IDM_RENAME_REMARK               32832
#define IDM_UPDATE_SERVER               32833
#define IDM_LOCAL_OPEN                  32834
#define IDM_REMOTE_OPEN_SHOW            32836
#define IDM_REMOTE_OPEN_HIDE            32837
#define IDM_AUDIO_LISTEN                32838
#define IDM_DISCONNECT                  32840
#define IDM_ALL_DELETE                  32846
#define IDM_EVENT_SAVE                  32847
#define IDM_EVENT_COPY                  32848
#define IDM_REFSESH_SER                 32849
#define IDM_ADSL_SAVE                   32849
#define IDM_START_SER                   32850
#define IDM_STOP_SER                    32851
#define IDM_DEL_SER                     32852
#define IDM_AUTO_SER                    32853
#define IDM_SERVICE                     32854
#define IDM_HAND_SER                    32854
#define IDM_REGEDIT                     32855
#define IDM_DIS_SER                     32855
#define IDM_SERVER                      32856
#define IDM_SETTING                     32857
#define IDM_BIND                        32858
#define IDM_UPDATE                      32859
#define IDM_BUILD                       32860
#define IDM_INSTALL                     32861
#define IDM_SHOWMSG                     32862
#define IDM_WINDOW                      32864
#define IDM_PROCESS                     32865
#define IDM_CHANGEGROUP                 32866
#define IDM_SKIN_QQ2009                 32867
#define IDM_SKIN_CHINA                  32868
#define IDM_SKIN_BLACK                  32869
#define IDM_SKIN_AERO                   32870
#define IDM_CLOSESKIN                   32871
#define ID_PROXY                        32872
#define IDM_PROXY                       32872
#define IDM_SYSINFO                     32886
#define IDM_DDOS                        32887
#define IDC_suoding                     32889
#define IDM_SKIN                        32890
#define IDM_IPUPDATE                    32893
#define IDM_CHANGEPASSWORD              32895
#define IDM_DELUSER                     32896
#define IDM_DISCONNECT_USER             32897
#define IDM_LOGOFF_USER                 32898
#define IDM_COPY                        32900
#define IDM_ACTIVE_USER                 32904
#define IDM_DISABLEUSER                 32905
#define IDM_REGT_DEL                    32938
#define IDM_REGT_CREAT                  32939
#define IDM_REGL_DELKEY                 32946
#define IDM_REGL_STR                    32948
#define IDM_REGL_DWORD                  32949
#define IDM_REGL_EXSTR                  32950
#define IDM_REGL_EDIT                   32951
#define IDM_EVENT_DELETE                42845
#define ID_STAUTSTIP                    59394
#define ID_STAUTSSPEED                  59395
#define ID_STAUTSPORT                   59396
#define ID_STAUTSCOUNT                  59397
#define ID_OS                           59398
#define IDC_SETTINGS                    65535
#define IDC_ZITIA                       65535

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        231
#define _APS_NEXT_COMMAND_VALUE         32891
#define _APS_NEXT_CONTROL_VALUE         1117
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
